<?php
// ============================================================
// Referral Network Portal — Supabase Setup Wizard
// ============================================================

$configFile = __DIR__ . '/config.php';
$step = 1;
$error = '';

if (file_exists($configFile) && !isset($_GET['reinstall'])) {
    header("Location: index.php");
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $host   = trim($_POST['db_host'] ?? '');
    $port   = trim($_POST['db_port'] ?? '5432');
    $user   = trim($_POST['db_user'] ?? 'postgres');
    $pass   = $_POST['db_pass'] ?? '';
    $dbname = trim($_POST['db_name'] ?? 'postgres');

    if (!$host || !$pass) {
        $error = 'Host and password are required.';
    } else {
        try {
            $pdo = new PDO(
                "pgsql:host=$host;port=$port;dbname=$dbname;sslmode=require",
                $user, $pass,
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );
            // Quick check — list tables
            $pdo->query("SELECT 1");
        } catch (PDOException $e) {
            $msg = $e->getMessage();
            if (strpos($msg, 'password') !== false || strpos($msg, '28') !== false) {
                $error = "Wrong password or username. Double-check your Supabase database password.";
            } elseif (strpos($msg, 'could not connect') !== false || strpos($msg, 'timeout') !== false) {
                $error = "Could not reach the host. Check the Supabase host address and that your internet is connected.";
            } else {
                $error = "Connection failed: $msg";
            }
        }
    }

    if (!$error) {
        $config = "<?php\n"
            . "// Auto-generated by install.php\n"
            . "define('DB_HOST', " . var_export($host,   true) . ");\n"
            . "define('DB_PORT', " . var_export($port,   true) . ");\n"
            . "define('DB_USER', " . var_export($user,   true) . ");\n"
            . "define('DB_PASS', " . var_export($pass,   true) . ");\n"
            . "define('DB_NAME', " . var_export($dbname, true) . ");\n";

        if (file_put_contents($configFile, $config) === false) {
            $error = "Cannot write config.php — check folder permissions.";
        } else {
            $step = 2;
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Setup — Referral Network Portal</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <style>
        *{box-sizing:border-box;margin:0;padding:0}
        body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f0f4f9;
             min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:20px}
        .card{background:#fff;border-radius:12px;padding:40px;width:100%;max-width:500px;
              box-shadow:0 4px 20px rgba(0,0,0,.08)}
        .logo{text-align:center;margin-bottom:28px}
        .logo-icon{width:52px;height:52px;background:#1F3864;color:#fff;border-radius:12px;
                   display:flex;align-items:center;justify-content:center;font-size:22px;margin:0 auto 10px}
        h1{font-size:20px;font-weight:700;color:#1a202c;text-align:center}
        .subtitle{font-size:13px;color:#718096;text-align:center;margin-top:4px}
        .steps{display:flex;gap:0;margin:20px 0;border-radius:8px;overflow:hidden;border:1px solid #e2e8f0}
        .step{flex:1;padding:10px;text-align:center;font-size:12px;font-weight:600;color:#718096;background:#f8fafc}
        .step.active{background:#1F3864;color:#fff}
        .step.done{background:#d1fae5;color:#065f46}
        .form-group{margin-bottom:14px}
        .form-group label{display:block;font-size:11px;font-weight:600;color:#718096;
                          text-transform:uppercase;letter-spacing:.5px;margin-bottom:5px}
        .form-group input,.form-group select{width:100%;border:1px solid #e2e8f0;border-radius:6px;
                           padding:9px 12px;font-size:13px;color:#1a202c;background:#fff}
        .form-group input:focus{outline:none;border-color:#1F3864;box-shadow:0 0 0 3px rgba(31,56,100,.1)}
        .hint{font-size:11px;color:#718096;margin-top:3px}
        .btn{width:100%;background:#1F3864;color:#fff;border:none;padding:11px;border-radius:7px;
             font-size:14px;font-weight:600;cursor:pointer;margin-top:8px;transition:background .15s}
        .btn:hover{background:#172d55}
        .alert-error{background:#fee2e2;color:#991b1b;border:1px solid #fca5a5;border-radius:8px;
                     padding:12px 16px;margin-bottom:16px;font-size:13px}
        .info-box{background:#eff6ff;border:1px solid #bfdbfe;border-radius:8px;padding:14px 16px;
                  margin-bottom:16px;font-size:13px;color:#1e40af}
        .info-box strong{display:block;margin-bottom:6px;font-size:13px}
        .info-box ol{margin-left:16px;line-height:2}
        code{background:#dbeafe;padding:2px 6px;border-radius:4px;font-size:12px;font-family:monospace}
        .row{display:grid;grid-template-columns:3fr 1fr;gap:10px}
        .checklist{list-style:none;margin:12px 0}
        .checklist li{display:flex;align-items:center;gap:8px;padding:7px 0;
                      font-size:13px;border-bottom:1px solid #f1f5f9}
        .checklist li i{color:#059669;font-size:15px;flex-shrink:0}
        .login-btn{display:flex;align-items:center;justify-content:center;gap:8px;width:100%;
                   background:#1F3864;color:#fff;border:none;padding:11px;border-radius:7px;
                   font-size:14px;font-weight:600;cursor:pointer;text-decoration:none;margin-top:20px}
        .login-btn:hover{background:#172d55}
        .accounts{background:#f8fafc;border-radius:8px;padding:12px 14px;font-size:12px;
                  color:#718096;margin-top:14px;line-height:1.8}
        .accounts strong{color:#1a202c}
        footer{margin-top:20px;font-size:11px;color:#718096;text-align:center}
        .divider{border:none;border-top:1px solid #e2e8f0;margin:20px 0}
    </style>
</head>
<body>
<div class="card">
    <div class="logo">
        <div class="logo-icon"><i class="bi bi-grid-3x3-gap-fill"></i></div>
        <h1>Referral Network Portal</h1>
        <p class="subtitle">Supabase Database Setup</p>
    </div>

    <?php if ($step === 1): ?>

    <div class="steps">
        <div class="step active">1 · Supabase Schema</div>
        <div class="step">2 · Connect</div>
        <div class="step">3 · Done</div>
    </div>

    <!-- Step 1 instructions -->
    <div class="info-box">
        <strong><i class="bi bi-1-circle-fill"></i> First — import the schema into Supabase</strong>
        <ol>
            <li>Go to <strong>supabase.com</strong> → your project</li>
            <li>Click <strong>SQL Editor</strong> in the left sidebar</li>
            <li>Click <strong>New Query</strong></li>
            <li>Open <code>database.sql</code> from this project, copy everything, paste it in, click <strong>Run</strong></li>
            <li>You should see "Success" — then come back here</li>
        </ol>
    </div>

    <hr class="divider">

    <!-- Step 2: connection details -->
    <div class="info-box" style="background:#f0fdf4;border-color:#bbf7d0;color:#065f46">
        <strong><i class="bi bi-2-circle-fill"></i> Then — get your connection details</strong>
        Supabase Dashboard → <strong>Project Settings</strong> → <strong>Database</strong> → scroll to <em>Connection parameters</em>
    </div>

    <?php if ($error): ?>
        <div class="alert-error"><i class="bi bi-exclamation-circle"></i> <?= $error ?></div>
    <?php endif; ?>

    <form method="POST">
        <div class="form-group row">
            <div>
                <label>Supabase Host</label>
                <input type="text" name="db_host"
                       value="<?= htmlspecialchars($_POST['db_host'] ?? '') ?>"
                       placeholder="db.xxxxxxxxxxxx.supabase.co" required>
                <div class="hint">Project Settings → Database → Host</div>
            </div>
            <div>
                <label>Port</label>
                <input type="text" name="db_port"
                       value="<?= htmlspecialchars($_POST['db_port'] ?? '5432') ?>">
            </div>
        </div>
        <div class="form-group">
            <label>Database User</label>
            <input type="text" name="db_user"
                   value="<?= htmlspecialchars($_POST['db_user'] ?? 'postgres') ?>">
            <div class="hint">Default is <code>postgres</code></div>
        </div>
        <div class="form-group">
            <label>Database Password</label>
            <input type="password" name="db_pass" placeholder="Your Supabase database password" required>
            <div class="hint">Project Settings → Database → Database Password</div>
        </div>
        <div class="form-group">
            <label>Database Name</label>
            <input type="text" name="db_name"
                   value="<?= htmlspecialchars($_POST['db_name'] ?? 'postgres') ?>">
            <div class="hint">Default is <code>postgres</code></div>
        </div>
        <button type="submit" class="btn"><i class="bi bi-plug-fill"></i> &nbsp;Connect &amp; Save</button>
    </form>

    <?php else: ?>

    <div class="steps">
        <div class="step done"><i class="bi bi-check"></i> Schema</div>
        <div class="step done"><i class="bi bi-check"></i> Connected</div>
        <div class="step active">3 · Done</div>
    </div>

    <div style="text-align:center;margin-bottom:20px">
        <div style="width:60px;height:60px;background:#d1fae5;border-radius:50%;
                    display:flex;align-items:center;justify-content:center;margin:0 auto 12px;font-size:28px;color:#059669">
            <i class="bi bi-check-lg"></i>
        </div>
        <h1 style="color:#059669">Connected!</h1>
        <p class="subtitle" style="margin-top:6px">Supabase is configured and ready.</p>
    </div>

    <ul class="checklist">
        <li><i class="bi bi-check-circle-fill"></i> Supabase connection verified</li>
        <li><i class="bi bi-check-circle-fill"></i> Credentials saved to <code>config.php</code></li>
        <li><i class="bi bi-check-circle-fill"></i> Works from any computer — no local MySQL needed</li>
    </ul>

    <div class="accounts">
        <strong>Default login accounts</strong> (password: <code>password</code>)<br>
        Partner &nbsp;→ <code>alex@partner.com</code><br>
        Broker &nbsp;&nbsp;→ <code>broker@networkportal.com</code><br>
        Admin &nbsp;&nbsp;→ <code>admin@networkportal.com</code><br>
        Auditor → <code>auditor@networkportal.com</code>
    </div>

    <a href="index.php" class="login-btn"><i class="bi bi-arrow-right"></i> Go to Login</a>

    <p style="text-align:center;margin-top:14px;font-size:12px;color:#718096">
        <i class="bi bi-shield-exclamation"></i> You can delete <code>install.php</code> after logging in.
    </p>

    <?php endif; ?>
</div>

<footer>&copy; <?= date('Y') ?> Referral Network Portal</footer>
</body>
</html>
